# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/moreau/dev/ens/TPosgAvions/TP-avions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/moreau/dev/ens/TPosgAvions/TP-avions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moreau/dev/ens/TPosgAvions/TP-avions/CMakeFiles /Users/moreau/dev/ens/TPosgAvions/TP-avions/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moreau/dev/ens/TPosgAvions/TP-avions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tp_avions

# Build rule for target.
tp_avions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tp_avions
.PHONY : tp_avions

# fast build rule for target.
tp_avions/fast:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/build
.PHONY : tp_avions/fast

Avion.o: Avion.cpp.o
.PHONY : Avion.o

# target to build an object file
Avion.cpp.o:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/Avion.cpp.o
.PHONY : Avion.cpp.o

Avion.i: Avion.cpp.i
.PHONY : Avion.i

# target to preprocess a source file
Avion.cpp.i:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/Avion.cpp.i
.PHONY : Avion.cpp.i

Avion.s: Avion.cpp.s
.PHONY : Avion.s

# target to generate assembly for a file
Avion.cpp.s:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/Avion.cpp.s
.PHONY : Avion.cpp.s

AvionAmi.o: AvionAmi.cpp.o
.PHONY : AvionAmi.o

# target to build an object file
AvionAmi.cpp.o:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionAmi.cpp.o
.PHONY : AvionAmi.cpp.o

AvionAmi.i: AvionAmi.cpp.i
.PHONY : AvionAmi.i

# target to preprocess a source file
AvionAmi.cpp.i:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionAmi.cpp.i
.PHONY : AvionAmi.cpp.i

AvionAmi.s: AvionAmi.cpp.s
.PHONY : AvionAmi.s

# target to generate assembly for a file
AvionAmi.cpp.s:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionAmi.cpp.s
.PHONY : AvionAmi.cpp.s

AvionEnnemi.o: AvionEnnemi.cpp.o
.PHONY : AvionEnnemi.o

# target to build an object file
AvionEnnemi.cpp.o:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionEnnemi.cpp.o
.PHONY : AvionEnnemi.cpp.o

AvionEnnemi.i: AvionEnnemi.cpp.i
.PHONY : AvionEnnemi.i

# target to preprocess a source file
AvionEnnemi.cpp.i:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionEnnemi.cpp.i
.PHONY : AvionEnnemi.cpp.i

AvionEnnemi.s: AvionEnnemi.cpp.s
.PHONY : AvionEnnemi.s

# target to generate assembly for a file
AvionEnnemi.cpp.s:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/AvionEnnemi.cpp.s
.PHONY : AvionEnnemi.cpp.s

GeneralCallback.o: GeneralCallback.cpp.o
.PHONY : GeneralCallback.o

# target to build an object file
GeneralCallback.cpp.o:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/GeneralCallback.cpp.o
.PHONY : GeneralCallback.cpp.o

GeneralCallback.i: GeneralCallback.cpp.i
.PHONY : GeneralCallback.i

# target to preprocess a source file
GeneralCallback.cpp.i:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/GeneralCallback.cpp.i
.PHONY : GeneralCallback.cpp.i

GeneralCallback.s: GeneralCallback.cpp.s
.PHONY : GeneralCallback.s

# target to generate assembly for a file
GeneralCallback.cpp.s:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/GeneralCallback.cpp.s
.PHONY : GeneralCallback.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tp_avions.dir/build.make CMakeFiles/tp_avions.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tp_avions"
	@echo "... Avion.o"
	@echo "... Avion.i"
	@echo "... Avion.s"
	@echo "... AvionAmi.o"
	@echo "... AvionAmi.i"
	@echo "... AvionAmi.s"
	@echo "... AvionEnnemi.o"
	@echo "... AvionEnnemi.i"
	@echo "... AvionEnnemi.s"
	@echo "... GeneralCallback.o"
	@echo "... GeneralCallback.i"
	@echo "... GeneralCallback.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

